twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    cache: '%kernel.cache_dir%/twig'
    strict_variables: false

when@test:
    twig:
        strict_variables: true
