services:
  nginx:  # Defines a service named "nginx"
    image: nginx:1.27.4-alpine  # Uses the official Nginx image with version 1.27.4 based on Alpine Linux (lightweight)
    ports:
      - "8080:80"  # Maps port 8080 on the host to port 80 inside the container (default for Nginx)
    volumes:
      - ./:/code:delegated  # Toujours en mode optimisé
      - ./nginx.conf:/etc/nginx/nginx.conf
    working_dir: /code  # Définit le dossier de travail pour éviter des chemins cassés
  php:
    build: .  # Searches for a Dockerfile in the current directory to build the PHP image
    volumes:
      - ./:/code:delegated  # Optimise la lecture des fichiers
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  mysql:
    image: mysql:latest  # Uses the latest official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: root  # Sets the root password for MySQL
      MYSQL_DATABASE: appdb  # Creates a database named "appdb"
      MYSQL_USER: user  # Creates a new user "user"
      MYSQL_PASSWORD: password  # Sets the password for the new user
    volumes:
      - data:/var/lib/mysql  # Persists MySQL data using a named volume
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf  # Optimisation MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  # Uses the official phpMyAdmin image
    environment:
      PMA_HOST: mysql  # Links phpMyAdmin to the MySQL service
      MYSQL_ROOT_PASSWORD: root  # Uses the same root password as MySQL
    ports:
      - "8081:80"

volumes:
  data:  # Defines a named volume for MySQL data persistence